modLoader="javafml"
loaderVersion="[47,)"
license="Public Domain"

[[mods]]
modId="basics_in_geometry"
version="1.0.2"
displayName="Basics In Geometry"
displayURL="https://www.curseforge.com/minecraft/mc-mods/basics-in-geometry"
credits="Coding by gabi_9b!"
authors="CreeperKing78"
description="Brace yourself for educational fun!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.basics_in_geometry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.basics_in_geometry]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration